import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PHOTOS_ROOT = resolve(__dirname, "../public/photos");
const OUTPUT_FILE = resolve(__dirname, "../src/data/generatedPhotos.ts");

const VALID_EXTENSIONS = [".jpg", ".jpeg", ".png", ".webp"];

type Category = "Portrait" | "Landscape" | "Events" | "Street";

const CATEGORY_MAP: Record<string, Category> = {
  portrait: "Portrait",
  landscape: "Landscape",
  street: "Street",
  events: "Events",
};

type Bucket = {
  folder: string;
  idPrefix: string;
  exportName: string;
};

const BUCKETS: Bucket[] = [
  { folder: "hero", idPrefix: "hero", exportName: "heroImages" },
  { folder: "gallery", idPrefix: "g", exportName: "galleryPhotos" },
  { folder: "behind-the-lens", idPrefix: "b", exportName: "behindTheLensPhotos" },
];

type FileEntry = {
  categories: Category[];
  categoryFolder: string;
  filename: string;
  sortPrefix: number | null;
  titleSlug: string;
};

function walkFiles(dir: string): { path: string; parentDir: string }[] {
  const results: { path: string; parentDir: string }[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walkFiles(fullPath));
    } else if (VALID_EXTENSIONS.includes(extname(entry.name).toLowerCase())) {
      results.push({ path: fullPath, parentDir: dir });
    }
  }
  return results;
}

function toTitleCase(slug: string): string {
  return slug
    .split("-")
    .filter(Boolean)
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join(" ");
}

function resolveCategories(categoryFolder: string, bucketDir: string): Category[] {
  const segments = categoryFolder.split("+").map((segment) => segment.trim());

  return segments.map((segment) => {
    const category = CATEGORY_MAP[segment.toLowerCase()];
    if (!category) {
      throw new Error(
        `Invalid category "${segment}" in folder "${categoryFolder}" under ${bucketDir}. ` +
          `Expected one of: ${Object.keys(CATEGORY_MAP).join(", ")}.`
      );
    }
    return category;
  });
}

function buildBucketEntries(bucketDir: string): FileEntry[] {
  if (!existsSync(bucketDir)) return [];

  return walkFiles(bucketDir).map(({ path, parentDir }) => {
    const categoryFolder = parentDir.split(/[\\/]/).pop()!;
    const categories = resolveCategories(categoryFolder, bucketDir);

    const filename = path.split(/[\\/]/).pop()!;
    const base = filename.slice(0, filename.length - extname(filename).length);
    const prefixMatch = base.match(/^(\d+)-(.+)$/);
    const sortPrefix = prefixMatch ? Number(prefixMatch[1]) : null;
    const titleSlug = prefixMatch ? prefixMatch[2] : base;

    return { categories, categoryFolder, filename, sortPrefix, titleSlug };
  });
}

function sortEntries(entries: FileEntry[]): FileEntry[] {
  return [...entries].sort((a, b) => {
    if (a.sortPrefix !== null && b.sortPrefix !== null) {
      return (
        a.sortPrefix - b.sortPrefix ||
        a.categoryFolder.localeCompare(b.categoryFolder) ||
        a.filename.localeCompare(b.filename)
      );
    }
    if (a.sortPrefix !== null) return -1;
    if (b.sortPrefix !== null) return 1;
    return a.titleSlug.localeCompare(b.titleSlug);
  });
}

function generateBucket(bucket: Bucket): { code: string; count: number } {
  const bucketDir = join(PHOTOS_ROOT, bucket.folder);
  const sorted = sortEntries(buildBucketEntries(bucketDir));

  const photos = sorted.map((entry, index) => ({
    id: `${bucket.idPrefix}-${index + 1}`,
    src: `/photos/${bucket.folder}/${entry.categoryFolder}/${entry.filename}`,
    title: toTitleCase(entry.titleSlug),
    categories: entry.categories,
  }));

  const entriesCode = photos
    .map(
      (photo) =>
        `  { id: ${JSON.stringify(photo.id)}, src: ${JSON.stringify(
          photo.src
        )}, title: ${JSON.stringify(photo.title)}, categories: ${JSON.stringify(
          photo.categories
        )} },`
    )
    .join("\n");

  const code = `export const ${bucket.exportName}: Photo[] = [\n${entriesCode}\n];\n`;
  return { code, count: photos.length };
}

const generated = BUCKETS.map(generateBucket);

const fileContents =
  `// AUTO-GENERATED FILE — DO NOT EDIT BY HAND.\n` +
  `// Generated by scripts/generate-photo-data.ts from files under /public/photos.\n` +
  `// Add, rename, or remove photos there and re-run \`npm run generate-photo-data\`\n` +
  `// (this also runs automatically as part of \`npm run build\`).\n\n` +
  `import type { Photo } from "./photos";\n\n` +
  generated.map((g) => g.code).join("\n");

writeFileSync(OUTPUT_FILE, fileContents);

console.log(
  `Generated src/data/generatedPhotos.ts (${BUCKETS.map(
    (b, i) => `${b.exportName}: ${generated[i].count}`
  ).join(", ")})`
);
