/**
 * Enumerates public/photos/gallery/<category>/* into src/data/galleryPhotos.ts
 * so the app has a single local photo pool with folder-derived categories and
 * intrinsic dimensions (used to pick portrait-only shots for the hero).
 *
 * Vite's import.meta.glob can't see files under public/, so this build step
 * (wired into `predev` and `build`, same as scripts/generate-seo-files.ts)
 * is how the folder is turned into data. Drop a new image into any of the
 * category folders and it appears after the next `npm run dev` / build.
 *
 * The generated file is gitignored — it is always rebuilt.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const GALLERY_ROOT = resolve(here, "../public/photos/gallery");
const OUTPUT_FILE = resolve(here, "../src/data/galleryPhotos.ts");

const VALID_EXT = new Set([".jpg", ".jpeg", ".png", ".webp"]);

// Folder name (lower-case) → the category label the UI already uses. A folder
// may combine categories with "+", e.g. "events+portrait".
const CATEGORY_MAP: Record<string, string> = {
  portrait: "Portrait",
  landscape: "Landscape",
  events: "Events",
  street: "Street",
};

function titleFromFilename(name: string): string {
  const slug = name
    .slice(0, name.length - extname(name).length)
    .replace(/^\d+[-_]+/, "");
  const words = slug
    .split(/[-_]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1));
  return words.join(" ") || "Untitled";
}

function jpegSize(buf: Buffer): { w: number; h: number } | null {
  let i = 2;
  while (i < buf.length) {
    if (buf[i] !== 0xff) {
      i++;
      continue;
    }
    const marker = buf[i + 1];
    if (
      marker >= 0xc0 &&
      marker <= 0xcf &&
      marker !== 0xc4 &&
      marker !== 0xc8 &&
      marker !== 0xcc
    ) {
      return { h: buf.readUInt16BE(i + 5), w: buf.readUInt16BE(i + 7) };
    }
    i += 2 + buf.readUInt16BE(i + 2);
  }
  return null;
}

function pngSize(buf: Buffer): { w: number; h: number } | null {
  if (buf.length < 24 || buf.toString("ascii", 12, 16) !== "IHDR") return null;
  return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
}

function imageSize(file: string): { w: number; h: number } {
  const ext = extname(file).toLowerCase();
  try {
    const buf = readFileSync(file);
    const size =
      ext === ".png" ? pngSize(buf) : ext === ".webp" ? null : jpegSize(buf);
    if (size) return size;
  } catch {
    /* fall through */
  }
  // Unknown (e.g. .webp) — 0×0 keeps it in the gallery but out of the
  // portrait-only hero pool.
  return { w: 0, h: 0 };
}

type Entry = {
  id: string;
  src: string;
  title: string;
  categories: string[];
  width: number;
  height: number;
};

const entries: Entry[] = [];

if (existsSync(GALLERY_ROOT)) {
  for (const folder of readdirSync(GALLERY_ROOT, { withFileTypes: true })) {
    if (!folder.isDirectory()) continue;

    const categories = folder.name.split("+").map((segment) => {
      const label = CATEGORY_MAP[segment.trim().toLowerCase()];
      if (!label) {
        throw new Error(
          `Unknown category folder "${folder.name}" (segment "${segment}") under ` +
            `public/photos/gallery/. Known: ${Object.keys(CATEGORY_MAP).join(", ")}.`
        );
      }
      return label;
    });

    const dir = join(GALLERY_ROOT, folder.name);
    for (const file of readdirSync(dir).sort()) {
      if (!VALID_EXT.has(extname(file).toLowerCase())) continue;
      const { w, h } = imageSize(join(dir, file));
      const base = file.slice(0, file.length - extname(file).length);
      entries.push({
        id: `g-${folder.name}-${base}`.replace(/[^a-zA-Z0-9_-]+/g, "-"),
        src: `/photos/gallery/${folder.name}/${file}`,
        title: titleFromFilename(file),
        categories,
        width: w,
        height: h,
      });
    }
  }
}

entries.sort((a, b) => a.src.localeCompare(b.src));

const body = `// AUTO-GENERATED by scripts/generate-gallery-photos.ts — do not edit by hand.
// Source of truth: public/photos/gallery/<category>/*
// Rebuild with: npm run generate-gallery-photos
import type { Photo } from "./photos";

export const galleryPhotos: Photo[] = ${JSON.stringify(entries, null, 2)};
`;

mkdirSync(dirname(OUTPUT_FILE), { recursive: true });
writeFileSync(OUTPUT_FILE, body);

console.log(
  `Generated ${entries.length} gallery photos → src/data/galleryPhotos.ts`
);
